apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
        - name: frontend-server
          image: frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE_URL
              value: http://gateway-server
            - name: VITE_JAVA_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-server
spec:
  selector:
    app: frontend-server
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173 
  type: LoadBalancer
